# Generated by Django 4.1 on 2022-09-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manyimage',
            old_name='item_images',
            new_name='item_img',
        ),
    ]
